apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: {{ .Values.app.deployment.replicas }}
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      # volumes:
      # - name: {{ tpl .Values.app.deployment.hostPath.name . }}
      #   hostPath:
      #     path: {{ tpl .Values.app.deployment.hostPath.mountPath . }}
      #     type: DirectoryOrCreate
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- range .Values.app.deployment.affinity.podAffinity.labelSelectors }}
            - labelSelector:
                {{- range .labelSelector.matchExpressions }}
                matchExpressions:
                  - key: {{ .key }}
                    operator: {{ .operator }}
                    values:
                      {{- range .values }}
                      - {{ tpl . $ }}
                        {{- end }}
              {{- end }}
              topologyKey: {{ .labelSelector.topologyKey }}
              namespaces:
                - {{ $.Release.Namespace }}
          {{- end }}
      containers:
      - name: keycloak
        image: {{ .Values.app.deployment.image }}
        args: {{ .Values.app.deployment.args }}
        # volumeMounts:
        # - mountPath: /ObjectStore
        #   name: {{ tpl .Values.app.deployment.hostPath.name . }}
        env:
        # - name: KC_LOG_LEVEL
        #   value: DEBUG
        # - name: QUARKUS_TRANSACTION_MANAGER_OBJECT_STORE_DIRECTORY
        #   value: /ObjectStore
        - name: QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY
          value: "true"
        - name: QUARKUS_TRANSACTION_TIMEOUT
          value: "36000"
        - name: QUARKUS_TRANSACTION_MANAGER_DEFAULT_TRANSACTION_TIMEOUT
          value: "36000"
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "true"
        - name: KC_HOSTNAME_URL
          value: {{ .Values.app.url }}
        - name: KC_HOSTNAME_ADMIN_URL
          value: {{ .Values.app.url }}
        - name: KC_PROXY
          value: passthrough
        - name: KEYCLOAK_STATISTICS
          value: {{ .Values.app.deployment.env.KEYCLOAK_STATISTICS }}
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              key: KEYCLOAK_ADMIN
              name: {{ .Values.secrets.admin.secretName }}
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: KEYCLOAK_ADMIN_PASSWORD
              name: {{ .Values.secrets.admin.secretName }}
        - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KC_DB
          value: {{ .Values.app.deployment.env.KC_DB }}
        - name: KC_DB_URL
          value: {{ .Values.app.deployment.env.KC_DB_URL }}
        - name: KC_DB_USERNAME
          value: root
        # - name: KC_DB_USERNAME
        #   valueFrom:
        #     secretKeyRef:
        #       key: MYSQL_USER
        #       name: '{{ .Release.Name }}-mysql-secret'
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: '{{ .Release.Name }}-mysql-secret'
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        resources:
          requests:
            cpu: {{ .Values.app.deployment.resources.requests.cpu }}
            memory: {{ .Values.app.deployment.resources.requests.memory }}
          limits:
            cpu: {{ .Values.app.deployment.resources.limits.cpu }}
            memory: {{ .Values.app.deployment.resources.limits.memory }}
