apiVersion: v1
kind: Secret
type: Opaque
data:
  MINIO_ROOT_USER: {{ .Values.secrets.minio.MINIO_ROOT_USER | b64enc }}
  MINIO_ROOT_PASSWORD: {{ .Values.secrets.minio.MINIO_ROOT_PASSWORD | b64enc }}
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
