apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 9000
    targetPort: 9000
  - name: console
    port: 9090
    targetPort: 9090
  selector:
    app: {{ .Release.Name }}