apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app: {{ tpl .Values.deployment.name . }}
  name: {{ tpl .Values.secrets.secretName . }}
data:
  DB_USER: {{ .Values.secrets.DB_USER | b64enc }}
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | b64enc }}