app:
  deployment:
    affinity:
      podAffinity:
        labelSelectors:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - '{{ tpl (index .Values "postgres" "deployment" "name") .
                }}'
            topologyKey: kubernetes.io/hostname
    env:
      APACHE_DISABLE_REWRITE_IP: 1
      OVERWRITEPROTOCOL: https
      TRUSTED_PROXIES: 10.0.0.0/8
    hostPath:
      mountPath: /eons/local/cloud/{{ .Release.Namespace }}/{{ .Release.Name }}/app
      name: app
    image: nextcloud:stable-apache
    priorityClass: prod-low
    resources:
      limits:
        cpu: 4000m
        memory: 4000Mi
      requests:
        cpu: 500m
        memory: 1000Mi
  domain: CHANGEME
  ingress:
    path: /
    secretName: nextcloud-letsencrypt-cert
postgres:
  deployment:
    affinity:
      nodeSelectors: {}
    #   - key: storage
    #     value: red1
    #   - key: db
    #     value: sync1
    db:
      auth: password
      name: nextcloud
    hostPath:
      mountPath: /eons/local/cloud/{{ .Release.Namespace }}/{{ .Release.Name }}/pg-data
      name: pg-data
    priorityClass: prod-low
    resources:
      limits:
        cpu: 4000m
        memory: 4000Mi
      requests:
        cpu: 500m
        memory: 1000Mi
  secrets:
    DB_PASSWORD: CHANGEME
    DB_USER: ncuser
secrets:
  letsencrypt:
    issuer: letsencrypt
    kind: ClusterIssuer
  nextcloudAdmin:
    NEXTCLOUD_ADMIN_PASSWORD: CHANGEME
    NEXTCLOUD_ADMIN_USER: CHANGEME
    secretName: nextcloud-admin-secrets
service:
  nextcloud:
    name: nextcloud-svc
  postgres:
    name: nextcloud-postgres-svc

redis:
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 100Mi
  secrets:
    REDIS_HOST_PASSWORD: CHANGEME